// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ControlUnit(	// \\src\\main\\scala\\main.scala:15:7
  input  [6:0] io_opcode,	// \\src\\main\\scala\\main.scala:16:14
  input  [2:0] io_funct3,	// \\src\\main\\scala\\main.scala:16:14
  input  [6:0] io_funct7,	// \\src\\main\\scala\\main.scala:16:14
  output [3:0] io_aluOp,	// \\src\\main\\scala\\main.scala:16:14
  output       io_regWen,	// \\src\\main\\scala\\main.scala:16:14
               io_memWen,	// \\src\\main\\scala\\main.scala:16:14
  output [1:0] io_src1Sel,	// \\src\\main\\scala\\main.scala:16:14
  output       io_src2Sel,	// \\src\\main\\scala\\main.scala:16:14
               io_wbSel,	// \\src\\main\\scala\\main.scala:16:14
               io_isSigned	// \\src\\main\\scala\\main.scala:16:14
);

  wire [3:0]      io_aluOp_0;	// \\src\\main\\scala\\main.scala:47:28, :72:17, :77:24, :82:23
  wire            isRType = io_opcode == 7'h33;	// \\src\\main\\scala\\main.scala:39:27
  wire            isIType = io_opcode == 7'h13;	// \\src\\main\\scala\\main.scala:40:27
  wire            isLoad = io_opcode == 7'h3;	// \\src\\main\\scala\\main.scala:41:27
  wire            isStore = io_opcode == 7'h23;	// \\src\\main\\scala\\main.scala:42:27
  wire            isLUI = io_opcode == 7'h37;	// \\src\\main\\scala\\main.scala:43:27
  wire            isAUIPC = io_opcode == 7'h17;	// \\src\\main\\scala\\main.scala:44:27
  wire            _GEN = isRType | isIType;	// \\src\\main\\scala\\main.scala:39:27, :40:27, :47:16
  wire            _GEN_0 = io_funct7 == 7'h20;	// \\src\\main\\scala\\main.scala:51:35
  wire [7:0][3:0] _GEN_1 =
    {{4'h9},
     {4'h8},
     {{3'h3, _GEN_0}},
     {4'h5},
     {4'h4},
     {4'h3},
     {4'h2},
     {{3'h0, isRType & _GEN_0}}};	// \\src\\main\\scala\\main.scala:32:14, :39:27, :48:23, :51:{22,35,53,64}, :52:31, :54:31, :55:31, :56:31, :57:31, :59:{42,53}, :60:31, :62:31, :63:31
  wire            _GEN_2 = isRType | isIType | isLoad;	// \\src\\main\\scala\\main.scala:34:14, :39:27, :40:27, :41:27, :72:17, :77:24, :82:23, :88:24
  assign io_aluOp_0 =
    _GEN | ~(isLoad | isStore | isLUI | isAUIPC | ~_GEN) ? _GEN_1[io_funct3] : 4'h0;	// \\src\\main\\scala\\main.scala:32:14, :41:27, :42:27, :43:27, :44:27, :47:{16,28}, :48:23, :51:53, :54:31, :55:31, :56:31, :57:31, :59:42, :62:31, :63:31, :72:17, :76:16, :77:24, :81:16, :82:23, :87:16, :88:24, :92:16, :93:22, :97:16, :98:24, :102:16
  assign io_aluOp = io_aluOp_0;	// \\src\\main\\scala\\main.scala:15:7, :47:28, :72:17, :77:24, :82:23
  assign io_regWen = _GEN_2 | ~isStore & (isLUI | isAUIPC);	// \\src\\main\\scala\\main.scala:15:7, :33:14, :34:14, :42:27, :43:27, :44:27, :72:17, :73:16, :77:24, :78:16, :82:23, :83:16, :88:24, :93:22, :94:16, :98:24
  assign io_memWen = ~_GEN_2 & isStore;	// \\src\\main\\scala\\main.scala:15:7, :34:14, :42:27, :72:17, :77:24, :82:23, :88:24
  assign io_src1Sel =
    isRType | isIType | isLoad | isStore ? 2'h0 : isLUI ? 2'h2 : {1'h0, isAUIPC};	// \\src\\main\\scala\\main.scala:15:7, :32:14, :35:14, :39:27, :40:27, :41:27, :42:27, :43:27, :44:27, :54:31, :72:17, :74:16, :77:24, :79:16, :82:23, :84:16, :88:24, :90:16, :93:22, :95:16, :98:24, :100:16
  assign io_src2Sel = ~isRType & (isIType | isLoad | isStore | isLUI | isAUIPC);	// \\src\\main\\scala\\main.scala:15:7, :39:27, :40:27, :41:27, :42:27, :43:27, :44:27, :72:17, :75:16, :77:24, :80:16, :82:23, :85:16, :88:24, :91:16, :93:22, :96:16, :98:24
  assign io_wbSel = ~_GEN & isLoad;	// \\src\\main\\scala\\main.scala:15:7, :41:27, :47:16, :72:17, :76:16, :77:24, :81:16, :82:23
  assign io_isSigned =
    io_aluOp_0 == 4'h0 | io_aluOp_0 == 4'h1 | io_aluOp_0 == 4'h3 | io_aluOp_0 == 4'h7;	// \\src\\main\\scala\\main.scala:15:7, :32:14, :47:28, :51:64, :55:31, :59:53, :66:28, :67:28, :68:{28,44}, :69:28, :72:17, :77:24, :82:23
endmodule

module RegisterFile(	// \\src\\main\\scala\\main.scala:178:7
  input         clock,	// <stdin>:172:11
                reset,	// <stdin>:173:11
  input  [4:0]  io_rs1,	// \\src\\main\\scala\\main.scala:179:14
                io_rs2,	// \\src\\main\\scala\\main.scala:179:14
                io_waddr,	// \\src\\main\\scala\\main.scala:179:14
  input  [31:0] io_wdata,	// \\src\\main\\scala\\main.scala:179:14
  input         io_wen,	// \\src\\main\\scala\\main.scala:179:14
  output [31:0] io_rdata1,	// \\src\\main\\scala\\main.scala:179:14
                io_rdata2	// \\src\\main\\scala\\main.scala:179:14
);

  reg  [31:0]       regs_0;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_1;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_2;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_3;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_4;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_5;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_6;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_7;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_8;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_9;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_10;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_11;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_12;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_13;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_14;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_15;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_16;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_17;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_18;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_19;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_20;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_21;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_22;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_23;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_24;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_25;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_26;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_27;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_28;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_29;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_30;	// \\src\\main\\scala\\main.scala:189:21
  reg  [31:0]       regs_31;	// \\src\\main\\scala\\main.scala:189:21
  wire [31:0][31:0] _GEN =
    {{regs_31},
     {regs_30},
     {regs_29},
     {regs_28},
     {regs_27},
     {regs_26},
     {regs_25},
     {regs_24},
     {regs_23},
     {regs_22},
     {regs_21},
     {regs_20},
     {regs_19},
     {regs_18},
     {regs_17},
     {regs_16},
     {regs_15},
     {regs_14},
     {regs_13},
     {regs_12},
     {regs_11},
     {regs_10},
     {regs_9},
     {regs_8},
     {regs_7},
     {regs_6},
     {regs_5},
     {regs_4},
     {regs_3},
     {regs_2},
     {regs_1},
     {regs_0}};	// \\src\\main\\scala\\main.scala:189:21, :191:19
  always @(posedge clock) begin	// <stdin>:172:11
    if (reset) begin	// <stdin>:172:11
      regs_0 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_1 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_2 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_3 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_4 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_5 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_6 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_7 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_8 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_9 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_10 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_11 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_12 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_13 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_14 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_15 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_16 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_17 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_18 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_19 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_20 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_21 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_22 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_23 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_24 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_25 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_26 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_27 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_28 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_29 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_30 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
      regs_31 <= 32'h0;	// \\src\\main\\scala\\main.scala:189:{21,29}
    end
    else begin	// <stdin>:172:11
      automatic logic _GEN_0 = io_wen & (|io_waddr);	// \\src\\main\\scala\\main.scala:194:{15,27}
      if (_GEN_0 & ~(|io_waddr))	// \\src\\main\\scala\\main.scala:189:21, :194:{15,27,36}, :195:20
        regs_0 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h1)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_1 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h2)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_2 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h3)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_3 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h4)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_4 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h5)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_5 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h6)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_6 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h7)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_7 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h8)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_8 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h9)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_9 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'hA)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_10 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'hB)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_11 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'hC)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_12 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'hD)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_13 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'hE)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_14 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'hF)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_15 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h10)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_16 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h11)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_17 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h12)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_18 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h13)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_19 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h14)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_20 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h15)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_21 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h16)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_22 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h17)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_23 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h18)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_24 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h19)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_25 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h1A)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_26 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h1B)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_27 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h1C)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_28 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h1D)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_29 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & io_waddr == 5'h1E)	// \\src\\main\\scala\\main.scala:178:7, :189:21, :194:{15,36}, :195:20
        regs_30 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
      if (_GEN_0 & (&io_waddr))	// \\src\\main\\scala\\main.scala:189:21, :194:{15,36}, :195:20
        regs_31 <= io_wdata;	// \\src\\main\\scala\\main.scala:189:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\main.scala:178:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\main.scala:178:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\main.scala:178:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\main.scala:178:7
      automatic logic [31:0] _RANDOM[0:31];	// \\src\\main\\scala\\main.scala:178:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\main.scala:178:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\main.scala:178:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\main.scala:178:7
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// \\src\\main\\scala\\main.scala:178:7
        end	// \\src\\main\\scala\\main.scala:178:7
        regs_0 = _RANDOM[5'h0];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_1 = _RANDOM[5'h1];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_2 = _RANDOM[5'h2];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_3 = _RANDOM[5'h3];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_4 = _RANDOM[5'h4];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_5 = _RANDOM[5'h5];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_6 = _RANDOM[5'h6];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_7 = _RANDOM[5'h7];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_8 = _RANDOM[5'h8];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_9 = _RANDOM[5'h9];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_10 = _RANDOM[5'hA];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_11 = _RANDOM[5'hB];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_12 = _RANDOM[5'hC];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_13 = _RANDOM[5'hD];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_14 = _RANDOM[5'hE];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_15 = _RANDOM[5'hF];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_16 = _RANDOM[5'h10];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_17 = _RANDOM[5'h11];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_18 = _RANDOM[5'h12];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_19 = _RANDOM[5'h13];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_20 = _RANDOM[5'h14];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_21 = _RANDOM[5'h15];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_22 = _RANDOM[5'h16];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_23 = _RANDOM[5'h17];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_24 = _RANDOM[5'h18];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_25 = _RANDOM[5'h19];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_26 = _RANDOM[5'h1A];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_27 = _RANDOM[5'h1B];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_28 = _RANDOM[5'h1C];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_29 = _RANDOM[5'h1D];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_30 = _RANDOM[5'h1E];	// \\src\\main\\scala\\main.scala:178:7, :189:21
        regs_31 = _RANDOM[5'h1F];	// \\src\\main\\scala\\main.scala:178:7, :189:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\main.scala:178:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\main.scala:178:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rdata1 = io_rs1 == 5'h0 ? 32'h0 : _GEN[io_rs1];	// \\src\\main\\scala\\main.scala:178:7, :189:29, :191:{19,27}
  assign io_rdata2 = io_rs2 == 5'h0 ? 32'h0 : _GEN[io_rs2];	// \\src\\main\\scala\\main.scala:178:7, :189:29, :191:19, :192:{19,27}
endmodule

module ImmGen(	// \\src\\main\\scala\\main.scala:109:7
  input  [31:0] io_inst,	// \\src\\main\\scala\\main.scala:110:14
  output [31:0] io_out	// \\src\\main\\scala\\main.scala:110:14
);

  assign io_out =
    io_inst[6:0] == 7'h23
      ? {{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}
      : io_inst[6:0] == 7'h37 | io_inst[6:0] == 7'h17
          ? {io_inst[31:12], 12'h0}
          : {{20{io_inst[31]}}, io_inst[31:20]};	// \\src\\main\\scala\\main.scala:109:7, :116:20, :119:{17,22,31,42}, :120:{17,22,42,56}, :121:{17,22}, :125:13, :126:{13,30,40}, src/main/scala/chisel3/util/Mux.scala:126:16
endmodule

module ALU(	// \\src\\main\\scala\\main.scala:134:7
  input  [31:0] io_a,	// \\src\\main\\scala\\main.scala:135:14
                io_b,	// \\src\\main\\scala\\main.scala:135:14
  input  [3:0]  io_aluOp,	// \\src\\main\\scala\\main.scala:135:14
  output [31:0] io_out,	// \\src\\main\\scala\\main.scala:135:14
  output        io_zf,	// \\src\\main\\scala\\main.scala:135:14
                io_of	// \\src\\main\\scala\\main.scala:135:14
);

  wire        _io_of_T_1 = io_aluOp == 4'h1;	// \\src\\main\\scala\\main.scala:148:25
  wire        isSub = _io_of_T_1 | io_aluOp == 4'h3 | io_aluOp == 4'h4;	// \\src\\main\\scala\\main.scala:148:{25,54,70,83}
  wire [31:0] adderB = {32{isSub}} ^ io_b;	// \\src\\main\\scala\\main.scala:148:70, :149:19
  wire [31:0] _sum_T_2 = io_a + adderB + {31'h0, isSub};	// \\src\\main\\scala\\main.scala:148:70, :149:19, :150:30, :155:35
  wire [62:0] _res_T = {31'h0, io_a} << io_b[4:0];	// \\src\\main\\scala\\main.scala:144:19, :155:35
  wire [31:0] _GEN = {27'h0, io_b[4:0]};	// \\src\\main\\scala\\main.scala:144:19, :161:35
  wire [31:0] res =
    ~(|io_aluOp) | io_aluOp == 4'h1
      ? _sum_T_2
      : io_aluOp == 4'h2
          ? _res_T[31:0]
          : io_aluOp == 4'h3
              ? {31'h0, $signed(io_a) < $signed(io_b)}
              : io_aluOp == 4'h4
                  ? {31'h0, io_a < io_b}
                  : io_aluOp == 4'h5
                      ? io_a ^ io_b
                      : io_aluOp == 4'h8
                          ? io_a | io_b
                          : io_aluOp == 4'h9
                              ? io_a & io_b
                              : io_aluOp == 4'h6
                                  ? io_a >> _GEN
                                  : io_aluOp == 4'h7
                                      ? $signed($signed(io_a) >>> _GEN)
                                      : 32'h0;	// \\src\\main\\scala\\main.scala:145:26, :148:{25,54,83}, :150:30, :152:20, :153:27, :154:27, :155:{27,35}, :156:{27,46}, :157:{27,39}, :158:{27,35}, :159:{27,35}, :160:{27,35}, :161:{27,35}, :162:{27,43}
  assign io_out = res;	// \\src\\main\\scala\\main.scala:134:7, :152:20, :153:27, :154:27
  assign io_zf = res == 32'h0;	// \\src\\main\\scala\\main.scala:134:7, :145:26, :152:20, :153:27, :154:27, :166:18
  assign io_of =
    (~(|io_aluOp) | _io_of_T_1) & io_a[31] == adderB[31] & _sum_T_2[31] != io_a[31];	// \\src\\main\\scala\\main.scala:134:7, :148:25, :149:19, :150:30, :152:20, :168:19, :169:21, :170:18, :171:{22,37,75,86,96}
endmodule

module AsyncInstMem(	// \\src\\main\\scala\\main.scala:202:7
  input  [7:0]  io_addr,	// \\src\\main\\scala\\main.scala:203:14
  output [31:0] io_inst	// \\src\\main\\scala\\main.scala:203:14
);

  wire [255:0][31:0] _GEN =
    '{32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h10002303,
      32'h10502023,
      32'h32128293,
      32'h876542B7,
      32'h8002203,
      32'h8402183,
      32'h8202223,
      32'hFF810113,
      32'h8002103,
      32'h8102023,
      32'hFFF00093};	// \\src\\main\\scala\\main.scala:223:11
  assign io_inst = _GEN[io_addr];	// \\src\\main\\scala\\main.scala:202:7, :223:11
endmodule

module AsyncDataMem(	// \\src\\main\\scala\\main.scala:229:7
  input         clock,	// <stdin>:625:11
                reset,	// <stdin>:626:11
  input  [31:0] io_addr,	// \\src\\main\\scala\\main.scala:230:14
                io_wdata,	// \\src\\main\\scala\\main.scala:230:14
  input         io_wen,	// \\src\\main\\scala\\main.scala:230:14
  output [31:0] io_rdata	// \\src\\main\\scala\\main.scala:230:14
);

  reg  [31:0]        mem_0;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_1;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_2;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_3;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_4;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_5;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_6;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_7;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_8;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_9;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_10;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_11;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_12;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_13;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_14;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_15;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_16;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_17;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_18;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_19;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_20;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_21;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_22;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_23;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_24;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_25;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_26;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_27;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_28;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_29;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_30;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_31;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_32;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_33;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_34;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_35;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_36;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_37;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_38;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_39;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_40;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_41;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_42;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_43;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_44;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_45;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_46;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_47;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_48;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_49;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_50;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_51;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_52;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_53;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_54;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_55;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_56;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_57;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_58;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_59;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_60;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_61;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_62;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_63;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_64;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_65;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_66;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_67;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_68;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_69;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_70;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_71;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_72;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_73;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_74;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_75;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_76;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_77;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_78;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_79;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_80;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_81;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_82;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_83;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_84;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_85;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_86;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_87;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_88;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_89;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_90;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_91;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_92;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_93;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_94;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_95;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_96;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_97;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_98;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_99;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_100;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_101;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_102;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_103;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_104;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_105;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_106;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_107;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_108;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_109;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_110;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_111;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_112;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_113;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_114;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_115;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_116;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_117;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_118;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_119;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_120;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_121;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_122;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_123;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_124;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_125;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_126;	// \\src\\main\\scala\\main.scala:239:20
  reg  [31:0]        mem_127;	// \\src\\main\\scala\\main.scala:239:20
  wire [127:0][31:0] _GEN =
    {{mem_127},
     {mem_126},
     {mem_125},
     {mem_124},
     {mem_123},
     {mem_122},
     {mem_121},
     {mem_120},
     {mem_119},
     {mem_118},
     {mem_117},
     {mem_116},
     {mem_115},
     {mem_114},
     {mem_113},
     {mem_112},
     {mem_111},
     {mem_110},
     {mem_109},
     {mem_108},
     {mem_107},
     {mem_106},
     {mem_105},
     {mem_104},
     {mem_103},
     {mem_102},
     {mem_101},
     {mem_100},
     {mem_99},
     {mem_98},
     {mem_97},
     {mem_96},
     {mem_95},
     {mem_94},
     {mem_93},
     {mem_92},
     {mem_91},
     {mem_90},
     {mem_89},
     {mem_88},
     {mem_87},
     {mem_86},
     {mem_85},
     {mem_84},
     {mem_83},
     {mem_82},
     {mem_81},
     {mem_80},
     {mem_79},
     {mem_78},
     {mem_77},
     {mem_76},
     {mem_75},
     {mem_74},
     {mem_73},
     {mem_72},
     {mem_71},
     {mem_70},
     {mem_69},
     {mem_68},
     {mem_67},
     {mem_66},
     {mem_65},
     {mem_64},
     {mem_63},
     {mem_62},
     {mem_61},
     {mem_60},
     {mem_59},
     {mem_58},
     {mem_57},
     {mem_56},
     {mem_55},
     {mem_54},
     {mem_53},
     {mem_52},
     {mem_51},
     {mem_50},
     {mem_49},
     {mem_48},
     {mem_47},
     {mem_46},
     {mem_45},
     {mem_44},
     {mem_43},
     {mem_42},
     {mem_41},
     {mem_40},
     {mem_39},
     {mem_38},
     {mem_37},
     {mem_36},
     {mem_35},
     {mem_34},
     {mem_33},
     {mem_32},
     {mem_31},
     {mem_30},
     {mem_29},
     {mem_28},
     {mem_27},
     {mem_26},
     {mem_25},
     {mem_24},
     {mem_23},
     {mem_22},
     {mem_21},
     {mem_20},
     {mem_19},
     {mem_18},
     {mem_17},
     {mem_16},
     {mem_15},
     {mem_14},
     {mem_13},
     {mem_12},
     {mem_11},
     {mem_10},
     {mem_9},
     {mem_8},
     {mem_7},
     {mem_6},
     {mem_5},
     {mem_4},
     {mem_3},
     {mem_2},
     {mem_1},
     {mem_0}};	// \\src\\main\\scala\\main.scala:239:20, :243:12
  always @(posedge clock) begin	// <stdin>:625:11
    if (reset) begin	// <stdin>:625:11
      mem_0 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_1 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_2 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_3 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_4 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_5 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_6 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_7 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_8 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_9 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_10 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_11 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_12 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_13 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_14 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_15 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_16 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_17 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_18 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_19 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_20 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_21 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_22 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_23 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_24 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_25 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_26 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_27 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_28 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_29 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_30 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_31 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_32 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_33 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_34 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_35 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_36 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_37 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_38 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_39 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_40 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_41 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_42 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_43 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_44 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_45 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_46 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_47 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_48 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_49 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_50 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_51 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_52 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_53 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_54 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_55 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_56 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_57 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_58 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_59 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_60 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_61 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_62 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_63 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_64 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_65 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_66 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_67 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_68 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_69 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_70 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_71 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_72 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_73 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_74 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_75 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_76 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_77 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_78 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_79 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_80 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_81 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_82 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_83 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_84 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_85 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_86 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_87 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_88 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_89 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_90 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_91 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_92 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_93 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_94 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_95 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_96 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_97 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_98 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_99 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_100 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_101 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_102 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_103 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_104 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_105 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_106 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_107 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_108 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_109 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_110 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_111 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_112 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_113 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_114 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_115 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_116 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_117 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_118 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_119 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_120 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_121 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_122 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_123 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_124 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_125 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_126 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
      mem_127 <= 32'h0;	// \\src\\main\\scala\\main.scala:239:{20,28}
    end
    else begin	// <stdin>:625:11
      if (io_wen & io_addr[8:2] == 7'h0)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_0 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h1)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_1 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h2)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_2 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h3)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_3 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h4)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_4 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h5)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_5 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h6)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_6 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h7)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_7 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h8)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_8 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h9)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_9 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'hA)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_10 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'hB)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_11 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'hC)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_12 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'hD)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_13 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'hE)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_14 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'hF)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_15 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h10)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_16 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h11)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_17 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h12)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_18 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h13)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_19 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h14)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_20 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h15)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_21 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h16)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_22 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h17)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_23 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h18)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_24 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h19)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_25 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h1A)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_26 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h1B)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_27 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h1C)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_28 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h1D)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_29 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h1E)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_30 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h1F)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_31 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h20)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_32 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h21)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_33 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h22)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_34 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h23)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_35 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h24)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_36 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h25)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_37 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h26)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_38 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h27)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_39 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h28)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_40 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h29)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_41 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h2A)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_42 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h2B)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_43 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h2C)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_44 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h2D)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_45 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h2E)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_46 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h2F)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_47 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h30)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_48 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h31)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_49 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h32)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_50 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h33)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_51 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h34)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_52 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h35)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_53 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h36)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_54 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h37)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_55 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h38)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_56 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h39)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_57 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h3A)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_58 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h3B)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_59 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h3C)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_60 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h3D)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_61 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h3E)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_62 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h3F)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_63 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h40)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_64 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h41)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_65 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h42)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_66 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h43)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_67 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h44)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_68 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h45)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_69 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h46)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_70 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h47)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_71 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h48)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_72 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h49)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_73 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h4A)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_74 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h4B)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_75 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h4C)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_76 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h4D)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_77 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h4E)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_78 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h4F)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_79 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h50)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_80 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h51)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_81 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h52)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_82 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h53)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_83 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h54)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_84 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h55)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_85 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h56)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_86 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h57)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_87 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h58)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_88 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h59)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_89 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h5A)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_90 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h5B)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_91 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h5C)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_92 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h5D)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_93 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h5E)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_94 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h5F)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_95 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h60)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_96 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h61)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_97 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h62)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_98 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h63)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_99 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h64)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_100 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h65)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_101 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h66)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_102 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h67)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_103 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h68)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_104 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h69)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_105 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h6A)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_106 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h6B)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_107 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h6C)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_108 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h6D)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_109 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h6E)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_110 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h6F)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_111 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h70)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_112 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h71)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_113 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h72)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_114 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h73)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_115 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h74)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_116 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h75)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_117 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h76)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_118 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h77)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_119 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h78)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_120 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h79)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_121 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h7A)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_122 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h7B)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_123 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h7C)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_124 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h7D)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_125 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & io_addr[8:2] == 7'h7E)	// \\src\\main\\scala\\main.scala:229:7, :239:20, :241:25, :245:16, :246:19
        mem_126 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
      if (io_wen & (&(io_addr[8:2])))	// \\src\\main\\scala\\main.scala:239:20, :241:25, :245:16, :246:19
        mem_127 <= io_wdata;	// \\src\\main\\scala\\main.scala:239:20
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\main.scala:229:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\main.scala:229:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\main.scala:229:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\main.scala:229:7
      automatic logic [31:0] _RANDOM[0:127];	// \\src\\main\\scala\\main.scala:229:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\main.scala:229:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\main.scala:229:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\main.scala:229:7
        for (logic [7:0] i = 8'h0; i < 8'h80; i += 8'h1) begin
          _RANDOM[i[6:0]] = `RANDOM;	// \\src\\main\\scala\\main.scala:229:7
        end	// \\src\\main\\scala\\main.scala:229:7
        mem_0 = _RANDOM[7'h0];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_1 = _RANDOM[7'h1];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_2 = _RANDOM[7'h2];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_3 = _RANDOM[7'h3];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_4 = _RANDOM[7'h4];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_5 = _RANDOM[7'h5];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_6 = _RANDOM[7'h6];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_7 = _RANDOM[7'h7];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_8 = _RANDOM[7'h8];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_9 = _RANDOM[7'h9];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_10 = _RANDOM[7'hA];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_11 = _RANDOM[7'hB];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_12 = _RANDOM[7'hC];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_13 = _RANDOM[7'hD];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_14 = _RANDOM[7'hE];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_15 = _RANDOM[7'hF];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_16 = _RANDOM[7'h10];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_17 = _RANDOM[7'h11];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_18 = _RANDOM[7'h12];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_19 = _RANDOM[7'h13];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_20 = _RANDOM[7'h14];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_21 = _RANDOM[7'h15];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_22 = _RANDOM[7'h16];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_23 = _RANDOM[7'h17];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_24 = _RANDOM[7'h18];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_25 = _RANDOM[7'h19];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_26 = _RANDOM[7'h1A];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_27 = _RANDOM[7'h1B];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_28 = _RANDOM[7'h1C];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_29 = _RANDOM[7'h1D];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_30 = _RANDOM[7'h1E];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_31 = _RANDOM[7'h1F];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_32 = _RANDOM[7'h20];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_33 = _RANDOM[7'h21];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_34 = _RANDOM[7'h22];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_35 = _RANDOM[7'h23];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_36 = _RANDOM[7'h24];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_37 = _RANDOM[7'h25];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_38 = _RANDOM[7'h26];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_39 = _RANDOM[7'h27];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_40 = _RANDOM[7'h28];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_41 = _RANDOM[7'h29];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_42 = _RANDOM[7'h2A];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_43 = _RANDOM[7'h2B];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_44 = _RANDOM[7'h2C];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_45 = _RANDOM[7'h2D];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_46 = _RANDOM[7'h2E];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_47 = _RANDOM[7'h2F];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_48 = _RANDOM[7'h30];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_49 = _RANDOM[7'h31];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_50 = _RANDOM[7'h32];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_51 = _RANDOM[7'h33];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_52 = _RANDOM[7'h34];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_53 = _RANDOM[7'h35];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_54 = _RANDOM[7'h36];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_55 = _RANDOM[7'h37];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_56 = _RANDOM[7'h38];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_57 = _RANDOM[7'h39];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_58 = _RANDOM[7'h3A];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_59 = _RANDOM[7'h3B];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_60 = _RANDOM[7'h3C];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_61 = _RANDOM[7'h3D];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_62 = _RANDOM[7'h3E];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_63 = _RANDOM[7'h3F];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_64 = _RANDOM[7'h40];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_65 = _RANDOM[7'h41];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_66 = _RANDOM[7'h42];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_67 = _RANDOM[7'h43];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_68 = _RANDOM[7'h44];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_69 = _RANDOM[7'h45];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_70 = _RANDOM[7'h46];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_71 = _RANDOM[7'h47];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_72 = _RANDOM[7'h48];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_73 = _RANDOM[7'h49];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_74 = _RANDOM[7'h4A];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_75 = _RANDOM[7'h4B];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_76 = _RANDOM[7'h4C];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_77 = _RANDOM[7'h4D];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_78 = _RANDOM[7'h4E];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_79 = _RANDOM[7'h4F];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_80 = _RANDOM[7'h50];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_81 = _RANDOM[7'h51];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_82 = _RANDOM[7'h52];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_83 = _RANDOM[7'h53];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_84 = _RANDOM[7'h54];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_85 = _RANDOM[7'h55];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_86 = _RANDOM[7'h56];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_87 = _RANDOM[7'h57];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_88 = _RANDOM[7'h58];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_89 = _RANDOM[7'h59];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_90 = _RANDOM[7'h5A];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_91 = _RANDOM[7'h5B];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_92 = _RANDOM[7'h5C];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_93 = _RANDOM[7'h5D];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_94 = _RANDOM[7'h5E];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_95 = _RANDOM[7'h5F];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_96 = _RANDOM[7'h60];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_97 = _RANDOM[7'h61];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_98 = _RANDOM[7'h62];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_99 = _RANDOM[7'h63];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_100 = _RANDOM[7'h64];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_101 = _RANDOM[7'h65];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_102 = _RANDOM[7'h66];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_103 = _RANDOM[7'h67];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_104 = _RANDOM[7'h68];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_105 = _RANDOM[7'h69];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_106 = _RANDOM[7'h6A];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_107 = _RANDOM[7'h6B];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_108 = _RANDOM[7'h6C];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_109 = _RANDOM[7'h6D];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_110 = _RANDOM[7'h6E];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_111 = _RANDOM[7'h6F];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_112 = _RANDOM[7'h70];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_113 = _RANDOM[7'h71];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_114 = _RANDOM[7'h72];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_115 = _RANDOM[7'h73];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_116 = _RANDOM[7'h74];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_117 = _RANDOM[7'h75];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_118 = _RANDOM[7'h76];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_119 = _RANDOM[7'h77];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_120 = _RANDOM[7'h78];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_121 = _RANDOM[7'h79];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_122 = _RANDOM[7'h7A];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_123 = _RANDOM[7'h7B];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_124 = _RANDOM[7'h7C];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_125 = _RANDOM[7'h7D];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_126 = _RANDOM[7'h7E];	// \\src\\main\\scala\\main.scala:229:7, :239:20
        mem_127 = _RANDOM[7'h7F];	// \\src\\main\\scala\\main.scala:229:7, :239:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\main.scala:229:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\main.scala:229:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rdata = _GEN[io_addr[8:2]];	// \\src\\main\\scala\\main.scala:229:7, :241:25, :243:12
endmodule

module SingleCycleCPU(	// \\src\\main\\scala\\main.scala:253:7
  input         clock,	// <stdin>:766:11
                reset,	// <stdin>:767:11
  output        io_zf,	// \\src\\main\\scala\\main.scala:254:14
                io_of,	// \\src\\main\\scala\\main.scala:254:14
  output [31:0] io_aluResult,	// \\src\\main\\scala\\main.scala:254:14
                io_currentInst,	// \\src\\main\\scala\\main.scala:254:14
                io_currentPC,	// \\src\\main\\scala\\main.scala:254:14
  output        io_isSignedOp,	// \\src\\main\\scala\\main.scala:254:14
                io_dmemWen,	// \\src\\main\\scala\\main.scala:254:14
  output [31:0] io_dmemAddr,	// \\src\\main\\scala\\main.scala:254:14
                io_dmemWData,	// \\src\\main\\scala\\main.scala:254:14
                io_dmemRData	// \\src\\main\\scala\\main.scala:254:14
);

  wire [31:0]      _dmem_io_rdata;	// \\src\\main\\scala\\main.scala:276:23
  wire [31:0]      _imem_io_inst;	// \\src\\main\\scala\\main.scala:275:23
  wire [31:0]      _alu_io_out;	// \\src\\main\\scala\\main.scala:274:23
  wire [31:0]      _immGen_io_out;	// \\src\\main\\scala\\main.scala:273:23
  wire [31:0]      _regFile_io_rdata1;	// \\src\\main\\scala\\main.scala:272:23
  wire [31:0]      _regFile_io_rdata2;	// \\src\\main\\scala\\main.scala:272:23
  wire [3:0]       _control_io_aluOp;	// \\src\\main\\scala\\main.scala:271:23
  wire             _control_io_regWen;	// \\src\\main\\scala\\main.scala:271:23
  wire             _control_io_memWen;	// \\src\\main\\scala\\main.scala:271:23
  wire [1:0]       _control_io_src1Sel;	// \\src\\main\\scala\\main.scala:271:23
  wire             _control_io_src2Sel;	// \\src\\main\\scala\\main.scala:271:23
  wire             _control_io_wbSel;	// \\src\\main\\scala\\main.scala:271:23
  reg  [31:0]      pcReg;	// \\src\\main\\scala\\main.scala:270:24
  wire [3:0][31:0] _GEN = {{32'h0}, {32'h0}, {pcReg}, {_regFile_io_rdata1}};	// \\src\\main\\scala\\main.scala:270:24, :272:23, :302:48
  always @(posedge clock) begin	// <stdin>:766:11
    if (reset)	// <stdin>:766:11
      pcReg <= 32'h0;	// \\src\\main\\scala\\main.scala:270:24
    else	// <stdin>:766:11
      pcReg <= pcReg + 32'h4;	// \\src\\main\\scala\\main.scala:270:24, :279:18
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\main.scala:253:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\main.scala:253:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\main.scala:253:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\main.scala:253:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\main.scala:253:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\main.scala:253:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\main.scala:253:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\main.scala:253:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\main.scala:253:7
        pcReg = _RANDOM[/*Zero width*/ 1'b0];	// \\src\\main\\scala\\main.scala:253:7, :270:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\main.scala:253:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\main.scala:253:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ControlUnit control (	// \\src\\main\\scala\\main.scala:271:23
    .io_opcode   (_imem_io_inst[6:0]),	// \\src\\main\\scala\\main.scala:275:23, :288:28
    .io_funct3   (_imem_io_inst[14:12]),	// \\src\\main\\scala\\main.scala:275:23, :289:28
    .io_funct7   (_imem_io_inst[31:25]),	// \\src\\main\\scala\\main.scala:275:23, :290:28
    .io_aluOp    (_control_io_aluOp),
    .io_regWen   (_control_io_regWen),
    .io_memWen   (_control_io_memWen),
    .io_src1Sel  (_control_io_src1Sel),
    .io_src2Sel  (_control_io_src2Sel),
    .io_wbSel    (_control_io_wbSel),
    .io_isSigned (io_isSignedOp)
  );
  RegisterFile regFile (	// \\src\\main\\scala\\main.scala:272:23
    .clock     (clock),
    .reset     (reset),
    .io_rs1    (_imem_io_inst[19:15]),	// \\src\\main\\scala\\main.scala:275:23, :296:27
    .io_rs2    (_imem_io_inst[24:20]),	// \\src\\main\\scala\\main.scala:275:23, :297:27
    .io_waddr  (_imem_io_inst[11:7]),	// \\src\\main\\scala\\main.scala:275:23, :298:27
    .io_wdata  (_control_io_wbSel ? _dmem_io_rdata : _alu_io_out),	// \\src\\main\\scala\\main.scala:271:23, :274:23, :276:23, :322:26
    .io_wen    (_control_io_regWen),	// \\src\\main\\scala\\main.scala:271:23
    .io_rdata1 (_regFile_io_rdata1),
    .io_rdata2 (_regFile_io_rdata2)
  );
  ImmGen immGen (	// \\src\\main\\scala\\main.scala:273:23
    .io_inst (_imem_io_inst),	// \\src\\main\\scala\\main.scala:275:23
    .io_out  (_immGen_io_out)
  );
  ALU alu (	// \\src\\main\\scala\\main.scala:274:23
    .io_a     (_GEN[_control_io_src1Sel]),	// \\src\\main\\scala\\main.scala:271:23, :302:48
    .io_b     (_control_io_src2Sel ? _immGen_io_out : _regFile_io_rdata2),	// \\src\\main\\scala\\main.scala:271:23, :272:23, :273:23, :308:17
    .io_aluOp (_control_io_aluOp),	// \\src\\main\\scala\\main.scala:271:23
    .io_out   (_alu_io_out),
    .io_zf    (io_zf),
    .io_of    (io_of)
  );
  AsyncInstMem imem (	// \\src\\main\\scala\\main.scala:275:23
    .io_addr (pcReg[9:2]),	// \\src\\main\\scala\\main.scala:270:24, :283:24
    .io_inst (_imem_io_inst)
  );
  AsyncDataMem dmem (	// \\src\\main\\scala\\main.scala:276:23
    .clock    (clock),
    .reset    (reset),
    .io_addr  (_alu_io_out),	// \\src\\main\\scala\\main.scala:274:23
    .io_wdata (_regFile_io_rdata2),	// \\src\\main\\scala\\main.scala:272:23
    .io_wen   (_control_io_memWen),	// \\src\\main\\scala\\main.scala:271:23
    .io_rdata (_dmem_io_rdata)
  );
  assign io_aluResult = _alu_io_out;	// \\src\\main\\scala\\main.scala:253:7, :274:23
  assign io_currentInst = _imem_io_inst;	// \\src\\main\\scala\\main.scala:253:7, :275:23
  assign io_currentPC = pcReg;	// \\src\\main\\scala\\main.scala:253:7, :270:24
  assign io_dmemWen = _control_io_memWen;	// \\src\\main\\scala\\main.scala:253:7, :271:23
  assign io_dmemAddr = _alu_io_out;	// \\src\\main\\scala\\main.scala:253:7, :274:23
  assign io_dmemWData = _regFile_io_rdata2;	// \\src\\main\\scala\\main.scala:253:7, :272:23
  assign io_dmemRData = _dmem_io_rdata;	// \\src\\main\\scala\\main.scala:253:7, :276:23
endmodule

